### ISSUE TITLE
Error: Cannot find source file:  C:/nxp/bstudio_nxp/sdk/JN-SW-4168/Components/ZigbeeCommon/Source/app_zps_link_keys.c

### ISSUE THREAD

**Issue by jalejandro0211** [grafalex82/hellozigbee#3] opened 2022-06-25 01:10 UTC
Hi, when I'm trying to build with command _cmake -G "MinGW Makefiles" -DTOOLCHAIN_PREFIX=C:/NXP/bstudio_nxp/sdk/Tools/ba-elf-ba2-r36379 -DSDK_PREFIX=C:/NXP/bstudio_nxp/sdk/JN-SW-4168 .._
I got and error:
```

CMake Error at src/CMakeLists.txt:92 (ADD_LIBRARY):
  Cannot find source file:

    C:/nxp/bstudio_nxp/sdk/JN-SW-4168/Components/ZigbeeCommon/Source/app_zps_link_keys.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at src/CMakeLists.txt:92 (ADD_LIBRARY):
  No SOURCES given to target: ZigBee


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Can you help me?

**Comment by devbis** [comment] 2022-06-25 13:19
You'd better use JN-SW-4170, e.g. from here https://github.com/739374663/JN-SW-4170

**Comment by jalejandro0211** [comment] 2022-06-29 02:23
> You'd better use JN-SW-4170, e.g. from here https://github.com/739374663/JN-SW-4170

Thanks @devbis.

I download the JN-SW-4170-Zigbee-3.0-v1745 from nxp as you said and compiles ok, thanks a lot!!!

**Comment by ferbulous** [comment] 2024-01-22 16:03
Hi @devbis , I'm having a similar issue even with JN-SW-4170 file
Is there anything I'm missing?

```
cmake -G "MinGW Makefiles" -DTOOLCHAIN_PREFIX=C:/NXP/bstudio_nxp/sdk/Tools/ba-elf-ba2-r36379 -DSDK_PREFIX=C:/NXP/bstudio_nxp/sdk/JN-SW-4170 ..
-- Using toolchain file: C:/Users/keel/Desktop/hellozigbee/cmake/JN5169.cmake
-- Configuring done (1.6s)
CMake Error at src/CMakeLists.txt:98 (ADD_LIBRARY):
  Cannot find source file:

    C:/NXP/bstudio_nxp/sdk/JN-SW-4170/Components/ZigbeeCommon/Source/app_zps_link_keys.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc


CMake Error at src/CMakeLists.txt:98 (ADD_LIBRARY):
  No SOURCES given to target: ZigBee


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by grafalex82** [comment] 2024-01-22 19:22
Did you install JN-SW-4170 at the C:/NXP/bstudio_nxp/sdk/JN-SW-4170 location?

**Comment by ferbulous** [comment] 2024-01-24 03:03
> Did you install JN-SW-4170 at the C:/NXP/bstudio_nxp/sdk/JN-SW-4170 location?

I reinstalled everything again except this time I'm using JN-SW-4170-Zigbee-3.0-v1745 instead of the v1840.
And that seems to work and after a few missing components installed, I'm able to compile the .bin firmware

**Comment by grafalex82** [comment] 2024-02-10 10:06
I assume that the issue is fixed, so I am closing the ticket. Please reopen or create a new one if necessary.

**Closed as completed by grafalex82** 2024-02-10 10:06 UTC
